data:extend {
{
    type = "item",
    icon = "__space-age__/graphics/icons/foundry.png",
    name = "crystallized-harene",
    stack_size = 500,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
{
    type = "item",
    icon = "__base__/graphics/icons/steel-plate.png",
    name = "haronite-plate",
    stack_size = 38,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
{
    type = "item",
    icon = "__space-age__/graphics/icons/foundry.png",
    name = "harene-ears-core",
    stack_size = 5,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
{
    type = "item",
    icon = "__space-age__/graphics/icons/foundry.png",
    name = "harene-engine",
    stack_size = 5,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
{
    type = "item",
    icon = "__space-age__/graphics/icons/nutrients.png",
    name = "rabbasca-carotene-powder",
    stack_size = 50,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
{
    type = "item",
    icon = "__space-age__/graphics/icons/big-volcanic-rock.png",
    name = "rabbasca-moonstone",
    stack_size = 50,
    subgroup = "transport",
    order = "b[personal-transport]-c[startertron]",
},
}